### ISSUE TITLE
Unable to monitor all statistics

### ISSUE THREAD

**Issue by crispygoth** [aerospike/aerospike-nagios#1]
The documentation [here](http://www.aerospike.com/docs/operations/monitor/nagios/) and in README.md both say that you can "monitor all general statistics" with:
`aerospike_nagios.py -h YOUR_ASD_HOST`

However when I attempt to do so I get the error message `A statistic was not supplied`.

**Comment by whyrg** [comment]
We have made the decision to simplify the nagios plugin due to feedback and as such, it no longer attempts any sort of aggregation or parsing of metrics (eg: trending, history) that are much better handled by 3rd party Nagios integrations like Check_MK or PNP4Nagios. 

The documentation error was an oversight and will be fixed shortly.
